sudo: false
language: node_js

branches:
  only:
    - master

jobs:
  after_success:
    - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    - git checkout master

  include:
    - stage: release
      node_js: lts/*

      script:
        - lerna run lint:all
        - lerna run test

      deploy:
        provider: script
        skip_cleanup: true
        script:
          - lerna publish --conventional-commits -y
