sudo: false
language: node_js

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*

      script:
        - lerna run lint:all
        - lerna run test

      deploy:
        provider: script
        skip_cleanup: true
        script:
          - git checkout master
          - lerna publish --conventional-commits -y
