sudo: false
language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  # - npm run test
  - npm run build

after_success:
  - npm run semantic-release
  - npm run deploy-storybook -- --out=docs --ci --host-token-env-variable=GITHUB_TOKEN
