name: React95 - Bojagi workflow

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email ggdaltoso@gmail.com
          git config --global user.name ggdaltoso
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --pure-lockfile --non-interactive
      - name: Bojagi
        run: |
          BOJAGI_SECRET=${BOJAGI_SECRET}
          yarn bojagi:core
        env:
          BOJAGI_SECRET: ${{ secrets.BOJAGI_SECRET }}
