name: Check PR

on:
  pull_request:
    branches:
      - master
jobs:
  check_pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Restoring cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn --pure-lockfile --non-interactive
    - name: Lint
      run: yarn lint:all
    - name: Test
      run: yarn test
    - name: Build
      run: yarn build
